2024-08-14 05:35:26,697 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'a1700b17-0e0e-4a40-a7e9-a85dc6015cbc', 'user_id': 'test_user', 'chatDate': datetime.datetime(2024, 8, 13, 20, 35, 26, 653574), 'topic_id': '1', 'fluency': 4, 'grammar': 6, 'vocabulary': 5, 'content': 7, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-14 05:35:26,748 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-14 07:24:22,877 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:07:11,105 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:10:36,955 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:14:26,602 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:25:46,380 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:28:17,906 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:30:06,996 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:35:20,377 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 10:53:47,619 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 11:05:10,539 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:13:13,279 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:20:05,939 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:36:19,701 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:44:23,826 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:24:36,859 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:47:50,723 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:48:14,984 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 14:00:04,910 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 16:32:53,813 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 16:38:17,157 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:21:37,833 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:33:16,647 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:34:11,020 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:43:32,413 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 09:02:03,910 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 09:48:16,273 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 10:24:04,524 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 11:41:08,353 ERROR: Error: llama runner process has terminated: exit status 0xc0000409 error:failed to create context with model 'C:\Users\begit\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa' [in C:\project\sesac\aiFriend\app\ai_chat.py:197]
2024-08-16 11:41:31,754 ERROR: Error: llama runner process has terminated: exit status 0xc0000409 error:failed to create context with model 'C:\Users\begit\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa' [in C:\project\sesac\aiFriend\app\ai_chat.py:197]
2024-08-16 12:01:49,707 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 13:42:21,727 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 14:05:45,216 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 14:26:13,668 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 14:44:18,369 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 16:12:19,048 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 16:31:28,993 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 17:39:20,040 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-17 12:29:41,740 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-22 16:49:05,168 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-22 16:51:48,423 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-22 16:59:21,859 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-22 17:07:20,734 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-23 13:16:29,385 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-23 14:53:25,658 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-23 14:54:41,938 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-23 14:55:08,897 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:53]
2024-08-23 14:58:25,276 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:02:32,713 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'c4ca51de-73b5-4a15-85fd-75e6a957ec87', 'user_id': 'test_user', 'chatDate': datetime.datetime(2024, 8, 23, 6, 2, 32, 600676), 'topic_id': '1', 'fluency': 6, 'grammar': 7, 'vocabulary': 5, 'content': 8, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-23 15:02:32,715 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-23 15:09:01,159 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:27:40,307 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:36:06,011 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:44:10,490 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:47:56,764 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:52]
2024-08-23 15:58:06,321 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 16:39:26,920 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 16:47:49,863 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 16:59:31,745 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:10:52,157 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:16:43,831 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:17:41,722 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:17:48,956 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:17:57,047 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:19:21,001 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:19:30,767 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:21:48,420 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:23:05,525 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:25:46,150 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:26:06,623 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:26:58,823 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:28:37,667 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:28:50,004 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:30:33,379 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:30:44,065 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:30:54,192 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:32:14,817 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:32:24,046 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:32:42,928 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:35:45,163 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:38:29,267 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
2024-08-23 17:40:27,320 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:46]
