2024-08-14 05:35:26,697 ERROR: Failed to save AI test result: (pymysql.err.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`aifriend`.`ai_chat_test`, CONSTRAINT `ai_chat_test_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topic` (`topic_id`))')
[SQL: INSERT INTO ai_chat_test (`chatTest_id`, user_id, `chatDate`, topic_id, fluency, grammar, vocabulary, content, `simpleEvaluation`) VALUES (%(chatTest_id)s, %(user_id)s, %(chatDate)s, %(topic_id)s, %(fluency)s, %(grammar)s, %(vocabulary)s, %(content)s, %(simpleEvaluation)s)]
[parameters: {'chatTest_id': 'a1700b17-0e0e-4a40-a7e9-a85dc6015cbc', 'user_id': 'test_user', 'chatDate': datetime.datetime(2024, 8, 13, 20, 35, 26, 653574), 'topic_id': '1', 'fluency': 4, 'grammar': 6, 'vocabulary': 5, 'content': 7, 'simpleEvaluation': "You're doing great."}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in C:\project\sesac\aiFriend\app\ai_chat.py:81]
2024-08-14 05:35:26,748 ERROR: Failed to save the test result to the database, but proceeding to send the response. [in C:\project\sesac\aiFriend\app\ai_chat.py:137]
2024-08-14 07:24:22,877 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:07:11,105 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:10:36,955 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:14:26,602 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:25:46,380 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:28:17,906 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:30:06,996 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 09:35:20,377 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 10:53:47,619 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 11:05:10,539 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:13:13,279 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:20:05,939 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:36:19,701 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 12:44:23,826 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:24:36,859 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:47:50,723 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 13:48:14,984 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-14 14:00:04,910 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 16:32:53,813 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 16:38:17,157 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:21:37,833 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:33:16,647 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:34:11,020 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-15 17:43:32,413 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 09:02:03,910 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 09:48:16,273 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 10:24:04,524 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
2024-08-16 11:41:08,353 ERROR: Error: llama runner process has terminated: exit status 0xc0000409 error:failed to create context with model 'C:\Users\begit\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa' [in C:\project\sesac\aiFriend\app\ai_chat.py:197]
2024-08-16 11:41:31,754 ERROR: Error: llama runner process has terminated: exit status 0xc0000409 error:failed to create context with model 'C:\Users\begit\.ollama\models\blobs\sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa' [in C:\project\sesac\aiFriend\app\ai_chat.py:197]
2024-08-16 12:01:49,707 INFO: App startup [in C:\project\sesac\aiFriend\app\__init__.py:51]
